# Generated by Django 3.2.8 on 2021-10-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('account', models.CharField(max_length=45, null=True)),
                ('phone_number', models.CharField(max_length=45)),
                ('telephon', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('mileage', models.IntegerField(default=0, null=True)),
                ('point', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('gender', models.BooleanField(null=True)),
                ('foreigner', models.BooleanField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
