# Generated by Django 3.2.8 on 2021-10-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telephon',
            new_name='telephone_number',
        ),
    ]
