# Generated by Django 3.2.7 on 2021-10-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(max_length=45)),
                ('receiver_phone_number', models.CharField(max_length=45)),
                ('order_number', models.CharField(max_length=45)),
                ('receiver_telephone', models.CharField(max_length=45, null=True)),
                ('receiver_address', models.CharField(max_length=200)),
                ('request', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Order_item_status_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_status_code', models.CharField(max_length=45)),
                ('order_item_status_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order_item_status_codes',
            },
        ),
        migrations.CreateModel(
            name='Order_status_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_code', models.CharField(max_length=45)),
                ('order_status_description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order_status_codes',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_tracking_number', models.CharField(max_length=45)),
                ('order_shipment_detail', models.CharField(max_length=200)),
                ('shipment_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(max_length=45)),
                ('size_value', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('order_item_status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_item_status_code')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_status_code'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='orders.Order_item', to='products.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
