# Generated by Django 3.2.8 on 2021-10-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='info_img',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
